//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiCBM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Clientes
    {
        public Nullable<int> Id_municipio { get; set; }
        public int Id_cliente { get; set; }
        public int Id_departamento { get; set; }
        public string Nombre { get; set; }
        public short Activo { get; set; }
        public string Apellido { get; set; }
        public string Cedula { get; set; }
        public string Direccion { get; set; }
        public string Num_telefono { get; set; }
        public string Sexo { get; set; }
        public string Email { get; set; }
    }
}
