//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiCBM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Empleados
    {
        public int Id_empleado { get; set; }
        public string Nombre_empleado { get; set; }
        public string Apellido { get; set; }
        public string Cargo { get; set; }
        public string Cedula { get; set; }
        public int Activo { get; set; }
    }
}
